# Generated by Django 6.0 on 2026-04-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.CharField(choices=[('publico', 'Agente Público'), ('paciente', 'Agente Paciente'), ('superusuario', 'Agente Superusuario')], max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('prompt', models.TextField(help_text='Prompt del sistema para este agente')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Agente',
                'verbose_name_plural': 'Configuración de Agentes',
            },
        ),
        migrations.CreateModel(
            name='ConversacionAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.CharField(choices=[('publico', 'Agente Público'), ('paciente', 'Agente Paciente'), ('superusuario', 'Agente Superusuario')], default='publico', max_length=20)),
                ('telefono', models.CharField(db_index=True, max_length=20)),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=10)),
                ('contenido', models.TextField()),
                ('modelo_usado', models.CharField(blank=True, max_length=60)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Agente',
                'verbose_name_plural': 'Historial de Agentes',
                'ordering': ['creado'],
            },
        ),
    ]
