# Generated by Django 6.0 on 2026-04-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModoHumano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=20, unique=True)),
                ('modo_humano', models.BooleanField(default=False)),
                ('sucursal_id', models.IntegerField(choices=[(3, 'Sede Japón'), (4, 'Sede Camacho')], default=3)),
                ('activado_por', models.CharField(blank=True, help_text='Quién activó el modo humano', max_length=100)),
                ('activado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modo Humano',
                'verbose_name_plural': 'Modos Humano',
                'ordering': ['-actualizado'],
            },
        ),
    ]
