# Generated by Django 6.0 on 2026-04-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0002_modohumano'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal_id', models.IntegerField(choices=[(3, 'Sede Japón'), (4, 'Sede Camacho')], unique=True)),
                ('ia_activa', models.BooleanField(default=True)),
                ('cambiado_por', models.CharField(blank=True, max_length=100)),
                ('cambiado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Control IA por Sucursal',
                'verbose_name_plural': 'Control IA por Sucursal',
            },
        ),
        migrations.AlterField(
            model_name='modohumano',
            name='activado_por',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
