# Generated by Django 6.0 on 2026-04-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0003_sucursalia_alter_modohumano_activado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, help_text='Número sin prefijo de país. Ej: 76543210', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de referencia — solo para identificar en el admin, no afecta la lógica', max_length=100)),
                ('agente', models.CharField(choices=[('superusuario', 'Agente Superusuario'), ('gerente', 'Agente Gerente'), ('recepcionista', 'Agente Recepcionista')], help_text='Agente que se asignará cuando este número escriba por WhatsApp', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff — Agente WhatsApp',
                'verbose_name_plural': 'Staff — Agentes WhatsApp',
                'ordering': ['agente', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='configagente',
            name='max_historial',
            field=models.PositiveIntegerField(default=20, help_text='Número máximo de mensajes del historial que se envían a la IA. Más mensajes = más contexto pero mayor costo. Recomendado: Público 20, Paciente 30, Recepcionista 15, Profesional 20, Gerente 15, Superusuario 10.'),
        ),
        migrations.AlterField(
            model_name='configagente',
            name='agente',
            field=models.CharField(choices=[('publico', 'Agente Público'), ('paciente', 'Agente Paciente'), ('superusuario', 'Agente Superusuario'), ('recepcionista', 'Agente Recepcionista'), ('profesional', 'Agente Profesional'), ('gerente', 'Agente Gerente')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='conversacionagente',
            name='agente',
            field=models.CharField(choices=[('publico', 'Agente Público'), ('paciente', 'Agente Paciente'), ('superusuario', 'Agente Superusuario'), ('recepcionista', 'Agente Recepcionista'), ('profesional', 'Agente Profesional'), ('gerente', 'Agente Gerente')], default='publico', max_length=20),
        ),
    ]
