# Generated by Django 6.0 on 2026-04-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0004_staffagente_configagente_max_historial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffagente',
            options={'verbose_name': 'Superusuario WhatsApp (Dueño)', 'verbose_name_plural': 'Superusuario WhatsApp (Dueño)'},
        ),
        migrations.RemoveField(
            model_name='staffagente',
            name='agente',
        ),
        migrations.AlterField(
            model_name='staffagente',
            name='nombre',
            field=models.CharField(help_text='Nombre de referencia — solo para identificar en el admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffagente',
            name='telefono',
            field=models.CharField(db_index=True, help_text='Número SIN prefijo de país. Ej: 76543210', max_length=20, unique=True),
        ),
    ]
