# Generated by Django 6.0 on 2026-04-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0005_alter_staffagente_options_remove_staffagente_agente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=20, unique=True)),
                ('paciente_id', models.IntegerField()),
                ('cual_tutor', models.CharField(default='tutor_1', max_length=10)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Selector de Paciente (tutor con varios hijos)',
                'verbose_name_plural': 'Selectores de Paciente (tutores con varios hijos)',
            },
        ),
    ]
