# Generated by Django 6.0 on 2026-04-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0006_selectorpaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionagente',
            name='origen',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('interno', 'Chat interno')], db_index=True, default='whatsapp', max_length=10),
        ),
    ]
