# Generated by Django 6.0 on 2026-07-25 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0005_tiposervicio_es_servicio_externo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Ítem',
                'verbose_name_plural': 'Categorías de Ítems',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('unidad', models.CharField(choices=[('unidad', 'Unidad'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('par', 'Par'), ('kit', 'Kit'), ('litro', 'Litro'), ('kg', 'Kilogramo'), ('resma', 'Resma')], default='unidad', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventario.categoriaiteminventario')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_inventario_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ítem de Inventario',
                'verbose_name_plural': 'Ítems de Inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TitularInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('centro', 'Centro (general)'), ('sucursal', 'Sucursal'), ('servicio', 'Servicio'), ('usuario', 'Usuario')], max_length=10)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulares_inventario', to='servicios.tiposervicio')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulares_inventario', to='servicios.sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulares_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Titular de Inventario',
                'verbose_name_plural': 'Titulares de Inventario',
            },
        ),
        migrations.CreateModel(
            name='StockInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='inventario.iteminventario')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventario.titularinventario')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'ordering': ['item__nombre'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de verificación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('motivo', models.CharField(choices=[('deja_de_trabajar', 'Profesional/usuario deja de trabajar'), ('dañado', 'Ítem dañado'), ('perdido', 'Ítem perdido'), ('reasignacion', 'Reasignación de trabajo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('notas_solicitante', models.CharField(blank=True, max_length=255)),
                ('notas_admin', models.CharField(blank=True, max_length=255)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='inventario.titularinventario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='inventario.iteminventario')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='inventario.titularinventario')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_resueltas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia de Inventario',
                'verbose_name_plural': 'Transferencias de Inventario',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada / Agregado'), ('ajuste', 'Ajuste (admin)'), ('transferencia_salida', 'Transferencia — salida'), ('transferencia_entrada', 'Transferencia — entrada'), ('baja', 'Baja / Eliminación (admin)')], max_length=25)),
                ('cantidad', models.IntegerField(help_text='Positivo = suma al stock, negativo = resta.')),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.iteminventario')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.titularinventario')),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.transferenciainventario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='titularinventario',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'centro')), fields=('tipo',), name='unico_titular_centro'),
        ),
        migrations.AddConstraint(
            model_name='titularinventario',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'sucursal')), fields=('tipo', 'sucursal'), name='unico_titular_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='titularinventario',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'servicio')), fields=('tipo', 'servicio'), name='unico_titular_servicio'),
        ),
        migrations.AddConstraint(
            model_name='titularinventario',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'usuario')), fields=('tipo', 'usuario'), name='unico_titular_usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='stockinventario',
            unique_together={('titular', 'item')},
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['-fecha'], name='inventario__fecha_2a2d27_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['titular', 'item'], name='inventario__titular_a3e8a6_idx'),
        ),
    ]
