# Generated by Django 6.0 on 2026-03-13 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_permisoedicionsesion'),
        ('egresos', '0001_initial'),
        ('facturacion', '0014_cuentacorriente_ingreso_neto_centro_and_more'),
        ('profesionales', '0002_profesional_foto'),
        ('servicios', '0005_tiposervicio_es_servicio_externo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaegreso',
            name='es_honorario_profesional',
            field=models.BooleanField(default=False, help_text='Marcar si esta categoría corresponde a pago de honorarios a profesionales externos', verbose_name='Es pago de honorarios'),
        ),
        migrations.AlterField(
            model_name='categoriaegreso',
            name='tipo',
            field=models.CharField(choices=[('arriendo', 'Arriendo / Alquiler'), ('servicios_basicos', 'Servicios Básicos'), ('personal', 'Personal Interno'), ('honorarios', 'Honorarios Profesionales'), ('equipamiento', 'Equipamiento y Materiales'), ('mantenimiento', 'Mantenimiento'), ('marketing', 'Marketing y Publicidad'), ('impuesto', 'Impuestos y Tasas'), ('seguro', 'Seguros'), ('capacitacion', 'Capacitación'), ('otro', 'Otro')], help_text='Agrupa la categoría para los reportes financieros', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Foto o PDF del comprobante del proveedor', upload_to='egresos/comprobantes/%Y/%m/', verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='numero_documento_proveedor',
            field=models.CharField(blank=True, help_text='Número de factura o recibo que el proveedor nos entregó', max_length=50, verbose_name='N° Doc. Proveedor'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='numero_egreso',
            field=models.CharField(help_text='Autogenerado: EGR-0001, EGR-0002, ...', max_length=20, unique=True, verbose_name='N° Egreso'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='periodo_mes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], help_text='Mes al que corresponde el gasto (puede diferir del mes de pago)', null=True, verbose_name='Período - Mes'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='sesiones_cubiertas',
            field=models.ManyToManyField(blank=True, help_text='Solo para honorarios: sesiones que cubre este pago', related_name='egreso_honorario', to='agenda.sesion', verbose_name='Sesiones cubiertas'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal a la que corresponde este egreso (vacío = global)', null=True, on_delete=django.db.models.deletion.PROTECT, to='servicios.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='egresorecurrente',
            name='dia_vencimiento',
            field=models.PositiveSmallIntegerField(default=1, help_text='Día del mes en que vence este egreso (1-28)', verbose_name='Día de vencimiento'),
        ),
        migrations.AlterField(
            model_name='egresorecurrente',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Dejar vacío si no tiene fecha de fin', null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='egresorecurrente',
            name='monto_estimado',
            field=models.DecimalField(decimal_places=0, help_text='El monto real puede ajustarse al generar el egreso', max_digits=10, verbose_name='Monto estimado (Bs.)'),
        ),
        migrations.AlterField(
            model_name='egresorecurrente',
            name='ultimo_generado',
            field=models.DateField(blank=True, help_text='Fecha del último Egreso generado desde esta plantilla', null=True, verbose_name='Último generado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='profesional',
            field=models.OneToOneField(blank=True, help_text='Vincular si este proveedor es un profesional registrado en el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor_egreso', to='profesionales.profesional', verbose_name='Profesional del sistema'),
        ),
        migrations.AlterField(
            model_name='resumenfinanciero',
            name='margen_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='resultado_neto / ingresos_netos × 100', max_digits=5, verbose_name='Margen (%)'),
        ),
        migrations.AlterField(
            model_name='resumenfinanciero',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Null = resumen global de todo el centro', null=True, on_delete=django.db.models.deletion.PROTECT, to='servicios.sucursal', verbose_name='Sucursal'),
        ),
        migrations.CreateModel(
            name='PagoHonorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_deuda', models.DecimalField(decimal_places=0, help_text='Suma de ComisionSesion.monto_profesional de las sesiones elegidas', max_digits=10, verbose_name='Deuda de las sesiones seleccionadas')),
                ('monto_pagado', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Monto pagado realmente')),
                ('diferencia', models.DecimalField(decimal_places=0, default=0, help_text='Positivo = faltó pagar. Negativo = se pagó de más (adelanto).', max_digits=10, verbose_name='Diferencia (deuda − pagado)')),
                ('saldado', models.BooleanField(default=False, help_text='Si está activo, las sesiones se consideran pagadas aunque el monto no cuadre.', verbose_name='Marcar como saldado')),
                ('fecha', models.DateField(verbose_name='Fecha de pago')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('egreso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago_honorario', to='egresos.egreso', verbose_name='Egreso (EGR-XXXX)')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.metodopago', verbose_name='Método de pago')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_honorarios', to='profesionales.profesional', verbose_name='Profesional')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_honorarios_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('sesiones', models.ManyToManyField(related_name='pago_honorario', to='agenda.sesion', verbose_name='Sesiones cubiertas')),
            ],
            options={
                'verbose_name': 'Pago de Honorario',
                'verbose_name_plural': 'Pagos de Honorarios',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
