# Generated by Django 6.0 on 2026-03-14 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0002_alter_categoriaegreso_es_honorario_profesional_and_more'),
        ('facturacion', '0014_cuentacorriente_ingreso_neto_centro_and_more'),
        ('servicios', '0005_tiposervicio_es_servicio_externo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resumenfinanciero',
            name='ingresos_adicionales',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Reembolsos, donaciones, alquileres, ajustes', max_digits=12, verbose_name='Ingresos adicionales'),
        ),
        migrations.CreateModel(
            name='IngresoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ingreso', models.CharField(help_text='Autogenerado: ING-0001, ING-0002, ...', max_length=20, unique=True, verbose_name='N° Ingreso')),
                ('tipo', models.CharField(choices=[('reembolso', 'Reembolso de Proveedor'), ('donacion', 'Donación / Subsidio'), ('alquiler', 'Alquiler de Espacio'), ('ajuste', 'Corrección / Ajuste Contable'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Ingreso')),
                ('fecha', models.DateField(verbose_name='Fecha de recepción')),
                ('concepto', models.CharField(max_length=300, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Monto (Bs.)')),
                ('periodo_mes', models.PositiveSmallIntegerField(blank=True, choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], null=True, verbose_name='Período - Mes')),
                ('periodo_anio', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Período - Año')),
                ('origen', models.CharField(blank=True, help_text='Nombre del proveedor, donante, inquilino, etc.', max_length=200, verbose_name='Origen / Fuente')),
                ('numero_documento', models.CharField(blank=True, help_text='Número de factura, recibo o documento de respaldo', max_length=50, verbose_name='N° Documento')),
                ('comprobante', models.FileField(blank=True, upload_to='egresos/ingresos_adicionales/%Y/%m/', verbose_name='Comprobante adjunto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('anulado', models.BooleanField(default=False, verbose_name='Anulado')),
                ('motivo_anulacion', models.TextField(blank=True, verbose_name='Motivo de anulación')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_adicionales_anulados', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.metodopago', verbose_name='Método de Recepción')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_adicionales_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('sucursal', models.ForeignKey(blank=True, help_text='Vacío = ingreso global del centro', null=True, on_delete=django.db.models.deletion.PROTECT, to='servicios.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Ingreso Adicional',
                'verbose_name_plural': 'Ingresos Adicionales',
                'ordering': ['-fecha', '-fecha_registro'],
                'indexes': [models.Index(fields=['fecha'], name='idx_ingadic_fecha'), models.Index(fields=['periodo_mes', 'periodo_anio'], name='idx_ingadic_periodo'), models.Index(fields=['anulado'], name='idx_ingadic_anulado')],
            },
        ),
    ]
