# Generated by Django 6.0 on 2025-12-26 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesionales', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, choices=[('profesional', 'Profesional'), ('recepcionista', 'Recepcionista'), ('gerente', 'Gerente')], help_text='Rol del usuario en el sistema', max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('profesional', models.OneToOneField(blank=True, help_text='Vinculación con el profesional (si es profesional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_usuario', to='profesionales.profesional')),
                ('sucursales', models.ManyToManyField(blank=True, help_text='Sucursales a las que tiene acceso este usuario', related_name='usuarios_asignados', to='servicios.sucursal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
