# Generated by Django 6.0 on 2026-01-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pacientes', '0002_alter_pacienteservicio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='paciente',
            field=models.OneToOneField(blank=True, help_text='Vinculación con el paciente (si es paciente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_usuario', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('paciente', 'Paciente'), ('profesional', 'Profesional'), ('recepcionista', 'Recepcionista'), ('gerente', 'Gerente')], help_text='Rol del usuario en el sistema', max_length=20, null=True),
        ),
    ]
