# Generated by Django 6.0 on 2026-02-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario_paciente_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tema_chat',
            field=models.CharField(choices=[('default', 'Normal'), ('arcoiris', 'Arcoíris'), ('oceano', 'Océano'), ('espacio', 'Espacio'), ('selva', 'Safari'), ('dulces', 'Dulces')], default='default', help_text='Tema visual del chat (aplica a todos los roles)', max_length=20),
        ),
    ]
