# Generated by Django 6.0 on 2026-03-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario_tema_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tema_calendario',
            field=models.CharField(blank=True, default='', help_text='Tema visual del calendario mágico elegido por el usuario', max_length=20),
        ),
    ]
