# Generated by Django 6.0 on 2026-03-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilusuario_tema_calendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tema_ui',
            field=models.CharField(choices=[('atardecer', 'Atardecer'), ('aurora', 'Aurora'), ('cyber', 'Cyber'), ('ocean', 'Océano'), ('forest', 'Bosque'), ('galaxy', 'Galaxia'), ('tropical', 'Tropical'), ('spring', 'Primavera'), ('sky', 'Cielo')], default='atardecer', help_text='Tema visual de la interfaz principal elegido por el usuario', max_length=20),
        ),
    ]
