# Generated by Django 6.0 on 2026-03-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilusuario_tema_ui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tema_ui',
            field=models.CharField(choices=[('atardecer', 'Atardecer Cálido'), ('aurora', 'Aurora Boreal'), ('cyber', 'Neón Cyberpunk'), ('ocean', 'Océano Profundo'), ('forest', 'Bosque Místico'), ('galaxy', 'Galaxia Rosa'), ('tropical', 'Atardecer Tropical'), ('spring', 'Primavera Clara'), ('sky', 'Cielo Abierto'), ('candy', 'Candy World'), ('dino', 'Mundo Dino'), ('space_kids', 'Espacio Cartoon'), ('rainbow', 'Arcoíris Mágico'), ('cartoon_night', 'Noche de Cuento'), ('pinguinos', 'Playa Pingüino'), ('gatito', 'Gatito Travieso'), ('ghost', 'Fantasmitas'), ('alien', 'Aliens Saltarines'), ('robot', 'Robots Locos'), ('osito', 'Ositos Dulces'), ('peces', 'Peces de Colores')], default='atardecer', help_text='Tema visual de la interfaz principal elegido por el usuario', max_length=20),
        ),
    ]
