# Generated by Django 6.0 on 2026-04-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_perfilusuario_tema_ui'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono (opcional, principalmente para Recepcionistas y Gerentes)', max_length=30, null=True),
        ),
    ]
