# Generated by Django 6.0 on 2026-07-23 20:57

import django.core.validators
import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0015_proyecto_archivo_informe_drive_url_and_more'),
        ('pacientes', '0007_paciente_direccion_escuela'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proyecto', 'Informe de Proyecto/Evaluación'), ('mensualidad', 'Informe de Mensualidad'), ('general', 'Documento General del Paciente')], default='general', max_length=20)),
                ('titulo', models.CharField(help_text='Nombre descriptivo del documento', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='documentos_pacientes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'jpg', 'jpeg', 'png', 'webp', 'xls', 'xlsx']), documentos.models.validar_tamano_archivo])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('mensualidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='agenda.mensualidad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pacientes.paciente')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='agenda.proyecto')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Paciente',
                'verbose_name_plural': 'Documentos de Pacientes',
                'ordering': ['-fecha_subida'],
                'indexes': [models.Index(fields=['paciente', '-fecha_subida'], name='documentos__pacient_ed0eb4_idx'), models.Index(fields=['proyecto'], name='documentos__proyect_7be13d_idx'), models.Index(fields=['mensualidad'], name='documentos__mensual_38e4ac_idx')],
            },
        ),
    ]
