# Generated by Django 6.0 on 2026-07-29 00:59
import django.core.validators
import documentos.models
import documentos.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documentopaciente_compartir_misael_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentopaciente',
            name='archivo',
            field=models.FileField(
                storage=documentos.storage_backends.get_documentos_storage(),
                upload_to='documentos_pacientes/%Y/%m/',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'jpg', 'jpeg', 'png', 'webp', 'xls', 'xlsx']
                    ),
                    documentos.models.validar_tamano_archivo,
                ],
            ),
        ),
    ]
