# Generated by Django 6.0 on 2026-08-09 03:55

import django.core.validators
import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_documentopaciente_archivo'),
        ('pacientes', '0008_alter_paciente_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesional_manual', models.CharField(blank=True, help_text='Solo completar si quien sube el plan NO es el propio profesional (ej. gerente o admin cargándolo en nombre de un profesional externo).', max_length=200, verbose_name='Nombre del profesional (si lo carga otro rol)')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del profesional')),
                ('area_intervencion', models.CharField(max_length=150, verbose_name='Área de intervención')),
                ('frecuencia_sesiones', models.CharField(blank=True, help_text='Ej: 2 veces por semana', max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Vacío = plan vigente', null=True)),
                ('proxima_revision', models.DateField(blank=True, help_text='Cuándo toca revisar/renovar el plan', null=True)),
                ('descripcion', models.TextField(help_text='Objetivos y lineamientos del plan')),
                ('notas_seguimiento', models.TextField(blank=True, help_text='Avances, observaciones, ajustes acordados')),
                ('archivo', models.FileField(blank=True, help_text='Informe o documento del plan, opcional', null=True, upload_to='planes_trabajo/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'jpg', 'jpeg', 'png', 'webp', 'xls', 'xlsx']), documentos.models.validar_tamano_archivo])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_trabajo', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(help_text='Quién creó el registro. Si es un profesional, su nombre se usa tal cual.', on_delete=django.db.models.deletion.PROTECT, related_name='planes_trabajo_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de trabajo',
                'verbose_name_plural': 'Planes de trabajo',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['paciente', '-fecha_inicio'], name='documentos__pacient_cd3c14_idx')],
            },
        ),
    ]
