# Generated by Django 6.0 on 2026-09-15 15:49

import django.core.validators
import documentos.models
import documentos.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_plantrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrabajo',
            name='archivo',
            field=models.FileField(blank=True, help_text='Informe o documento del plan, opcional', null=True, storage=documentos.storage_backends.R2DocumentosStorage(), upload_to='planes_trabajo/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'jpg', 'jpeg', 'png', 'webp', 'xls', 'xlsx']), documentos.models.validar_tamano_archivo]),
        ),
    ]
