# Generated by Django 5.1.15 on 2026-10-08 19:46

import django.core.validators
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_alter_plantrabajo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrabajo',
            name='archivo',
            field=models.FileField(blank=True, help_text='Informe o documento del plan, opcional', null=True, upload_to='planes_trabajo/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'jpg', 'jpeg', 'png', 'webp', 'xls', 'xlsx']), documentos.models.validar_tamano_archivo]),
        ),
    ]
