# Generated by Django 6.0 on 2025-12-13 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('profesionales', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('hora_real_inicio', models.TimeField(blank=True, help_text='Hora real de inicio (para sesiones con retraso)', null=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('realizada_retraso', 'Realizada con retraso'), ('cancelada', 'Cancelada'), ('permiso', 'Permiso (con aviso)'), ('falta', 'Falta sin aviso'), ('reprogramada', 'Reprogramada')], default='programada', max_length=20)),
                ('motivo_cambio', models.TextField(blank=True, help_text='Motivo de cancelación, falta, permiso o reprogramación')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales de la sesión')),
                ('fecha_reprogramada', models.DateField(blank=True, help_text='Nueva fecha cuando se reprograma', null=True)),
                ('hora_reprogramada', models.TimeField(blank=True, help_text='Nueva hora cuando se reprograma', null=True)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto base en Bs.', max_digits=10)),
                ('monto_cobrado', models.DecimalField(decimal_places=2, default=0, help_text='Monto final a cobrar en Bs.', max_digits=10)),
                ('porcentaje_cobro', models.DecimalField(decimal_places=2, default=100.0, help_text='Porcentaje que representa el monto cobrado', max_digits=5)),
                ('motivo_ajuste', models.TextField(blank=True, help_text='Motivo del ajuste de precio')),
                ('se_cobra', models.BooleanField(default=True, help_text='Si se cobra esta sesión')),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profesionales.profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.tiposervicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.sucursal')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
    ]
