# Generated by Django 6.0 on 2025-12-19 20:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('profesionales', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del proyecto (ej: EVAL-PSI-001)', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del proyecto', max_length=200)),
                ('tipo', models.CharField(choices=[('evaluacion', 'Evaluación'), ('tratamiento_especial', 'Tratamiento Especial'), ('otro', 'Otro')], max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField(blank=True, help_text='Fecha estimada de finalización', null=True)),
                ('fecha_fin_real', models.DateField(blank=True, help_text='Fecha real de finalización', null=True)),
                ('costo_total', models.DecimalField(decimal_places=2, help_text='Costo FIJO del proyecto completo', max_digits=10)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_progreso', 'En Progreso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planificado', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del alcance del proyecto')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_modificados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='pacientes.paciente')),
                ('profesional_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_responsable', to='profesionales.profesional')),
                ('servicio_base', models.ForeignKey(help_text='Servicio base (ej: Evaluación Psicológica)', on_delete=django.db.models.deletion.PROTECT, to='servicios.tiposervicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.sucursal')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('realizada_retraso', 'Realizada con Retraso'), ('falta', 'Falta sin Aviso'), ('permiso', 'Permiso (con aviso)'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='programada', max_length=20)),
                ('fecha_reprogramada', models.DateField(blank=True, null=True)),
                ('hora_reprogramada', models.TimeField(blank=True, null=True)),
                ('motivo_reprogramacion', models.TextField(blank=True)),
                ('reprogramacion_realizada', models.BooleanField(default=False, help_text='Marcar cuando ya se creó manualmente la nueva sesión')),
                ('hora_real_inicio', models.TimeField(blank=True, help_text='Hora real de inicio si hubo retraso', null=True)),
                ('minutos_retraso', models.PositiveIntegerField(blank=True, help_text='Minutos de retraso', null=True)),
                ('monto_cobrado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto a cobrar por esta sesión (0 si es parte de proyecto o gratuita)', max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('notas_sesion', models.TextField(blank=True, help_text='Notas clínicas/evolución de la sesión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_modificadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='profesionales.profesional')),
                ('proyecto', models.ForeignKey(blank=True, help_text='Si pertenece a un proyecto (evaluación, tratamiento especial)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='agenda.proyecto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='servicios.tiposervicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='servicios.sucursal')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['paciente', '-fecha_inicio'], name='agenda_proy_pacient_97226b_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['estado'], name='agenda_proy_estado_20ee2d_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['codigo'], name='agenda_proy_codigo_800f46_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['fecha', 'hora_inicio'], name='agenda_sesi_fecha_03f5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['paciente', 'fecha'], name='agenda_sesi_pacient_02aaee_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['profesional', 'fecha'], name='agenda_sesi_profesi_39e30f_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['estado'], name='agenda_sesi_estado_adb238_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['proyecto'], name='agenda_sesi_proyect_d2d654_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesion',
            constraint=models.UniqueConstraint(fields=('paciente', 'fecha', 'hora_inicio'), name='unique_paciente_fecha_hora'),
        ),
    ]
