# Generated by Django 6.0 on 2025-12-14 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('profesionales', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['fecha', 'hora_inicio'], 'verbose_name': 'Sesión', 'verbose_name_plural': 'Sesiones'},
        ),
        migrations.RenameField(
            model_name='sesion',
            old_name='creado_en',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='sesion',
            old_name='actualizado_en',
            new_name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='confirmada_por',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='fecha_confirmacion',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='motivo_ajuste',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='motivo_cambio',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='porcentaje_cobro',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='se_cobra',
        ),
        migrations.AddField(
            model_name='sesion',
            name='creada_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_creadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='minutos_retraso',
            field=models.PositiveIntegerField(blank=True, help_text='Minutos de retraso', null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='modificada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesion',
            name='motivo_reprogramacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='notas_sesion',
            field=models.TextField(blank=True, help_text='Notas clínicas/evolución de la sesión'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('realizada_retraso', 'Realizada con Retraso'), ('falta', 'Falta sin Aviso'), ('permiso', 'Permiso (con aviso)'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='programada', max_length=20),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fecha_reprogramada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='hora_real_inicio',
            field=models.TimeField(blank=True, help_text='Hora real de inicio si hubo retraso', null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='hora_reprogramada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='monto_cobrado',
            field=models.DecimalField(decimal_places=2, help_text='Monto a cobrar por esta sesión', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='profesionales.profesional'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='servicios.tiposervicio'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='servicios.sucursal'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['fecha', 'hora_inicio'], name='agenda_sesi_fecha_03f5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['paciente', 'fecha'], name='agenda_sesi_pacient_02aaee_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['profesional', 'fecha'], name='agenda_sesi_profesi_39e30f_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['estado'], name='agenda_sesi_estado_adb238_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['pagado'], name='agenda_sesi_pagado_9ed160_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesion',
            constraint=models.UniqueConstraint(fields=('paciente', 'fecha', 'hora_inicio'), name='unique_paciente_fecha_hora'),
        ),
    ]
