# Generated by Django 6.0 on 2025-12-26 18:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='monto_cobrado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto a cobrar por esta sesión (0 si es parte de proyecto/evaluación o gratuita)', max_digits=10),
        ),
    ]
