# Generated by Django 6.0 on 2026-01-19 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_sesion_monto_cobrado'),
        ('profesionales', '0002_profesional_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='editada_por_profesional',
            field=models.BooleanField(default=False, help_text='Indica si un profesional ya editó esta sesión'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='fecha_edicion_profesional',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el profesional editó la sesión', null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='profesional_editor',
            field=models.ForeignKey(blank=True, help_text='Profesional que editó la sesión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_editadas', to='profesionales.profesional'),
        ),
    ]
