# Generated by Django 6.0 on 2025-12-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_sesion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='reprogramacion_realizada',
            field=models.BooleanField(default=False, help_text='Marcar cuando ya se creó manualmente la nueva sesión'),
        ),
    ]
