# Generated by Django 6.0 on 2026-01-23 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_sesion_editada_por_profesional_and_more'),
        ('pacientes', '0005_paciente_user'),
        ('profesionales', '0002_profesional_foto'),
        ('servicios', '0002_sucursal_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la mensualidad (ej: MEN-2024-01-001)', max_length=20, unique=True)),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Mes (1-12)')),
                ('anio', models.PositiveIntegerField(help_text='Año')),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de días de la semana [0=Lunes, 6=Domingo]')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de las sesiones')),
                ('duracion_minutos', models.PositiveIntegerField(default=60, help_text='Duración de cada sesión en minutos')),
                ('costo_mensual', models.DecimalField(decimal_places=2, help_text='Costo TOTAL del mes (no por sesión)', max_digits=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensualidades_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mensualidades_modificadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensualidades', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensualidades', to='profesionales.profesional')),
                ('servicio', models.ForeignKey(help_text='Servicio base de la mensualidad', on_delete=django.db.models.deletion.PROTECT, related_name='mensualidades', to='servicios.tiposervicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensualidades', to='servicios.sucursal')),
            ],
            options={
                'verbose_name': 'Mensualidad',
                'verbose_name_plural': 'Mensualidades',
                'ordering': ['-anio', '-mes', '-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='sesion',
            name='mensualidad',
            field=models.ForeignKey(blank=True, help_text='Si pertenece a una mensualidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='agenda.mensualidad'),
        ),
        migrations.AddIndex(
            model_name='mensualidad',
            index=models.Index(fields=['paciente', '-anio', '-mes'], name='agenda_mens_pacient_e1b4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='mensualidad',
            index=models.Index(fields=['estado'], name='agenda_mens_estado_00bc1f_idx'),
        ),
        migrations.AddIndex(
            model_name='mensualidad',
            index=models.Index(fields=['codigo'], name='agenda_mens_codigo_8a3eae_idx'),
        ),
        migrations.AddConstraint(
            model_name='mensualidad',
            constraint=models.UniqueConstraint(fields=('paciente', 'servicio', 'mes', 'anio'), name='unique_mensualidad_paciente_servicio_periodo'),
        ),
    ]
