# Generated by Django 6.0 on 2026-01-24 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_mensualidad_sesion_mensualidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensualidad',
            name='dias_semana',
        ),
        migrations.RemoveField(
            model_name='mensualidad',
            name='duracion_minutos',
        ),
        migrations.RemoveField(
            model_name='mensualidad',
            name='hora_inicio',
        ),
    ]
