# Generated by Django 6.0 on 2026-01-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_remove_mensualidad_dias_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensualidad',
            name='codigo',
            field=models.CharField(help_text='Código único de la mensualidad (ej: PSICO-JUA-MEN-2026-03-001)', max_length=30, unique=True),
        ),
    ]
