# Generated by Django 6.0 on 2026-01-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_mensualidad_codigo'),
        ('profesionales', '0002_profesional_foto'),
        ('servicios', '0004_tiposervicio_precio_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioProfesionalMensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Servicio-Profesional',
                'verbose_name_plural': 'Servicios-Profesionales',
            },
        ),
        migrations.RemoveConstraint(
            model_name='mensualidad',
            name='unique_mensualidad_paciente_servicio_periodo',
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='codigo',
            field=models.CharField(help_text='Código único de la mensualidad (ej: MULTI-JUA-MEN-2026-03-001)', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='servicioprofesionalmensualidad',
            name='mensualidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_profesionales', to='agenda.mensualidad'),
        ),
        migrations.AddField(
            model_name='servicioprofesionalmensualidad',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profesionales.profesional'),
        ),
        migrations.AddField(
            model_name='servicioprofesionalmensualidad',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.tiposervicio'),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='servicios',
            field=models.ManyToManyField(related_name='mensualidades', through='agenda.ServicioProfesionalMensualidad', to='servicios.tiposervicio'),
        ),
        migrations.RemoveField(
            model_name='mensualidad',
            name='profesional',
        ),
        migrations.RemoveField(
            model_name='mensualidad',
            name='servicio',
        ),
        migrations.AlterUniqueTogether(
            name='servicioprofesionalmensualidad',
            unique_together={('mensualidad', 'servicio')},
        ),
    ]
