# Generated by Django 6.0 on 2026-01-26 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_servicioprofesionalmensualidad_and_more'),
        ('pacientes', '0005_paciente_user'),
        ('servicios', '0004_tiposervicio_precio_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mensualidad',
            constraint=models.UniqueConstraint(fields=('paciente', 'anio', 'mes'), name='unique_paciente_periodo'),
        ),
    ]
