# Generated by Django 6.0 on 2026-02-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_mensualidad_unique_paciente_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='monto_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto acordado al crear la sesión (referencia histórica, no afecta cálculos)', max_digits=10, null=True),
        ),
    ]
