# Generated by Django 6.0 on 2026-02-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_sesion_monto_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualidad',
            name='costo_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio acordado al crear la mensualidad (referencia histórica, no afecta cálculos)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='costo_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio acordado al crear el proyecto (referencia histórica, no afecta cálculos)', max_digits=10, null=True),
        ),
    ]
