# Generated by Django 6.0 on 2026-02-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_mensualidad_costo_original_proyecto_costo_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='monto_previo_exencion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio guardado automáticamente antes de exentar la sesión (permiso/cancelada/reprogramada). Se usa para restaurar el cobro si el estado vuelve a uno con costo.', max_digits=10, null=True),
        ),
    ]
