# Generated by Django 6.0 on 2026-03-03 00:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_sesion_monto_previo_exencion'),
        ('profesionales', '0002_profesional_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoEdicionSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sesion_desde', models.DateField(verbose_name='Sesiones desde')),
                ('fecha_sesion_hasta', models.DateField(verbose_name='Sesiones hasta')),
                ('valido_desde', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Válido desde')),
                ('valido_hasta', models.DateTimeField(verbose_name='Válido hasta')),
                ('puede_editar_estado', models.BooleanField(default=True, verbose_name='Puede editar estado')),
                ('puede_editar_notas', models.BooleanField(default=True, verbose_name='Puede editar notas')),
                ('puede_editar_otros_campos', models.BooleanField(default=False, verbose_name='Puede editar otros campos')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo del permiso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False, verbose_name='Fue usado')),
                ('fecha_uso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de uso')),
                ('otorgado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_otorgados', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_edicion', to='profesionales.profesional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Permiso de Edición',
                'verbose_name_plural': 'Permisos de Edición',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
