# Generated by Django 6.0 on 2026-04-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_permisoedicionsesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_entrega_informe',
            field=models.DateField(blank=True, help_text='Fecha en que se entregó el informe físico', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='informe_entregado',
            field=models.BooleanField(default=False, help_text='Indica si el informe físico fue entregado al tutor'),
        ),
    ]
