# Generated by Django 6.0 on 2026-04-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_proyecto_fecha_entrega_informe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='observaciones_informe',
            field=models.TextField(blank=True, help_text='Observaciones sobre la entrega del informe físico'),
        ),
    ]
