# Generated by Django 6.0 on 2026-04-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_proyecto_observaciones_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='archivo_informe_drive_url',
            field=models.URLField(blank=True, default='', help_text='Enlace al PDF del informe subido en Google Drive'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='archivo_informe_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre del archivo subido', max_length=255),
        ),
    ]
