# Generated by Django 6.0 on 2026-07-27 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_proyecto_archivo_informe_drive_url_and_more'),
        ('pacientes', '0007_paciente_direccion_escuela'),
        ('profesionales', '0002_profesional_foto'),
        ('servicios', '0005_tiposervicio_es_servicio_externo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['paciente', 'servicio', 'estado', '-fecha', '-hora_inicio'], name='idx_sesion_ult_pac_serv_edo'),
        ),
    ]
