# Generated by Django 6.0 on 2025-12-19 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('nombre_tutor', models.CharField(max_length=200)),
                ('parentesco', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('tutor', 'Tutor Legal'), ('abuelo', 'Abuelo/a'), ('tio', 'Tío/a'), ('hermano', 'Hermano/a'), ('otro', 'Otro')], default='tutor', help_text='Relación del tutor con el paciente', max_length=20)),
                ('telefono_tutor', models.CharField(max_length=20)),
                ('email_tutor', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('observaciones_medicas', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('sucursales', models.ManyToManyField(help_text='Sucursales donde puede ser atendido el paciente', related_name='pacientes', to='servicios.sucursal')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PacienteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_sesion', models.DecimalField(decimal_places=2, help_text='Costo en Bs. por sesión (puede personalizarse por paciente)', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tiposervicio')),
            ],
            options={
                'verbose_name': 'Servicio del Paciente',
                'verbose_name_plural': 'Servicios de Pacientes',
            },
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['estado'], name='pacientes_p_estado_8c5b22_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['apellido', 'nombre'], name='pacientes_p_apellid_72499c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pacienteservicio',
            unique_together={('paciente', 'servicio')},
        ),
    ]
