# Generated by Django 6.0 on 2025-12-16 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sucursal',
            field=models.ForeignKey(default=1, help_text='Sucursal donde se atiende el paciente', on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='servicios.sucursal'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['sucursal', 'estado'], name='pacientes_p_sucursa_833e8c_idx'),
        ),
    ]
