# Generated by Django 6.0 on 2025-12-26 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacienteservicio',
            options={'ordering': ['-activo', 'servicio__nombre'], 'verbose_name': 'Servicio del Paciente', 'verbose_name_plural': 'Servicios de los Pacientes'},
        ),
        migrations.RemoveIndex(
            model_name='paciente',
            name='pacientes_p_estado_8c5b22_idx',
        ),
        migrations.RemoveIndex(
            model_name='paciente',
            name='pacientes_p_apellid_72499c_idx',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_actualizacion',
            new_name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='pacienteservicio',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Diagnóstico o motivo de consulta'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='parentesco',
            field=models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('tutor', 'Tutor/a Legal'), ('abuelo', 'Abuelo/a'), ('tio', 'Tío/a'), ('hermano', 'Hermano/a'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sucursales',
            field=models.ManyToManyField(help_text='Sucursales donde puede ser atendido este paciente', related_name='pacientes', to='servicios.sucursal'),
        ),
        migrations.AlterField(
            model_name='pacienteservicio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está inactivo, no se puede programar sesiones con este servicio'),
        ),
        migrations.AlterField(
            model_name='pacienteservicio',
            name='costo_sesion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo por sesión para este paciente (se autocompleta con el precio base)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacienteservicio',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pacienteservicio',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones específicas sobre este servicio para el paciente'),
        ),
        migrations.AlterField(
            model_name='pacienteservicio',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='pacienteservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='servicios.tiposervicio'),
        ),
    ]
