# Generated by Django 6.0 on 2025-12-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_sucursal_and_more'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paciente',
            name='pacientes_p_sucursa_833e8c_idx',
        ),
        migrations.AddField(
            model_name='paciente',
            name='parentesco',
            field=models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('tutor', 'Tutor Legal'), ('abuelo', 'Abuelo/a'), ('tio', 'Tío/a'), ('hermano', 'Hermano/a'), ('otro', 'Otro')], default='tutor', help_text='Relación del tutor con el paciente', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sucursales',
            field=models.ManyToManyField(help_text='Sucursales donde puede ser atendido el paciente', related_name='pacientes', to='servicios.sucursal'),
        ),
        migrations.AlterField(
            model_name='pacienteservicio',
            name='costo_sesion',
            field=models.DecimalField(decimal_places=2, help_text='Costo en Bs. por sesión (puede personalizarse por paciente)', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['estado'], name='pacientes_p_estado_8c5b22_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['apellido', 'nombre'], name='pacientes_p_apellid_72499c_idx'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sucursal',
        ),
    ]
