# Generated by Django 6.0 on 2026-01-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_pacienteservicio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email_tutor_2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Segundo Tutor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_tutor_2',
            field=models.CharField(blank=True, help_text='Información del segundo tutor o contacto de emergencia (opcional)', max_length=200, null=True, verbose_name='Nombre del Segundo Tutor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='parentesco_2',
            field=models.CharField(blank=True, choices=[('madre', 'Madre'), ('padre', 'Padre'), ('tutor', 'Tutor/a Legal'), ('abuelo', 'Abuelo/a'), ('tio', 'Tío/a'), ('hermano', 'Hermano/a'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Parentesco del Segundo Tutor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_tutor_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Segundo Tutor'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email_tutor',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Tutor'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre_tutor',
            field=models.CharField(max_length=200, verbose_name='Nombre del Tutor Principal'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='parentesco',
            field=models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('tutor', 'Tutor/a Legal'), ('abuelo', 'Abuelo/a'), ('tio', 'Tío/a'), ('hermano', 'Hermano/a'), ('otro', 'Otro')], max_length=20, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_tutor',
            field=models.CharField(max_length=20, verbose_name='Teléfono del Tutor'),
        ),
    ]
