# Generated by Django 6.0 on 2026-01-14 15:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_email_tutor_2_paciente_nombre_tutor_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Foto del paciente (se optimizará automáticamente)', max_length=255, null=True, verbose_name='foto'),
        ),
    ]
