# Generated by Django 6.0 on 2026-01-16 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario del sistema vinculado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to=settings.AUTH_USER_MODEL),
        ),
    ]
