# Generated by Django 6.0 on 2026-04-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_paciente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='apoyo_escolar',
            field=models.BooleanField(default=False, help_text='Indica si el paciente cuenta con apoyos, adaptaciones o necesidades educativas especiales en la escuela', verbose_name='¿Recibe apoyo o adaptaciones curriculares?'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email_escuela',
            field=models.EmailField(blank=True, help_text='Email institucional del centro educativo o del maestro/a de referencia', max_length=254, null=True, verbose_name='Email de la Escuela o Maestro/a'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='grado_curso',
            field=models.CharField(blank=True, help_text='Ej: 3° de Primaria, Kínder, Inicial 2', max_length=100, null=True, verbose_name='Grado o Curso'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_escuela',
            field=models.CharField(blank=True, help_text='Nombre del colegio, escuela o centro educativo donde asiste', max_length=200, null=True, verbose_name='Nombre de la Escuela / Centro Educativo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_maestro',
            field=models.CharField(blank=True, help_text='Maestro/a principal o tutor educativo de referencia', max_length=200, null=True, verbose_name='Nombre del Maestro/a de Referencia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observaciones_escuela',
            field=models.TextField(blank=True, help_text='Notas sobre desempeño escolar, coordinación con el centro o información relevante del entorno educativo', verbose_name='Observaciones Educativas'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_escuela',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de la Escuela'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='turno_escolar',
            field=models.CharField(blank=True, choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('completo', 'Completo')], help_text='Turno en el que asiste al centro educativo', max_length=10, null=True, verbose_name='Turno Escolar'),
        ),
    ]
