# Generated by Django 6.0 on 2026-04-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_apoyo_escolar_paciente_email_escuela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='direccion_escuela',
            field=models.TextField(blank=True, help_text='Dirección o ubicación del colegio/escuela', null=True, verbose_name='Dirección del Centro Educativo'),
        ),
    ]
