# Generated by Django 6.0 on 2026-03-20 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('profesionales', '0002_profesional_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionadir',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_adir_realizadas', to='profesionales.profesional', verbose_name='Evaluador'),
        ),
        migrations.AlterField(
            model_name='evaluacionados2',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_ados2_realizadas', to='profesionales.profesional', verbose_name='Evaluador'),
        ),
        migrations.AlterField(
            model_name='informeevaluacion',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_generados', to='profesionales.profesional', verbose_name='Evaluador responsable'),
        ),
    ]
