# Generated by Django 6.0 on 2026-04-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual')], default='automatico', max_length=20)),
                ('exitoso', models.BooleanField(default=False)),
                ('tamanio_mb', models.CharField(blank=True, max_length=20)),
                ('duracion_segundos', models.FloatField(blank=True, null=True)),
                ('destinatarios', models.TextField(blank=True)),
                ('mensaje_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de Backup',
                'verbose_name_plural': 'Registros de Backup',
                'ordering': ['-fecha'],
            },
        ),
    ]
