# Generated by Django 6.0 on 2026-10-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichacontenido',
            name='huella_fuente',
            field=models.CharField(blank=True, editable=False, help_text='Hash del texto tal como lo entregó la última sincronización. Permite detectar si la ficha fue editada a mano (y entonces no sobrescribirla).', max_length=64),
        ),
        migrations.AlterField(
            model_name='fichacontenido',
            name='fuente',
            field=models.CharField(choices=[('manual', 'Escrita a mano'), ('servicios_data', 'Sincronizada desde las páginas públicas (core.servicios_data)'), ('tipo_servicio', 'Sincronizada desde TipoServicio'), ('sucursales', 'Sincronizada desde las sucursales')], default='manual', max_length=20),
        ),
    ]
