# Generated by Django 6.0 on 2026-02-16 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario_1', models.ForeignKey(help_text='Primer participante de la conversación', on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_usuario1', to=settings.AUTH_USER_MODEL)),
                ('usuario_2', models.ForeignKey(help_text='Segundo participante de la conversación', on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_usuario2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-ultima_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=1000)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.conversacion')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='chat.conversacion')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='chat.mensaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de Chat',
                'verbose_name_plural': 'Notificaciones de Chat',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['usuario_1', 'usuario_2'], name='chat_conver_usuario_50c690_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['-ultima_actualizacion'], name='chat_conver_ultima__7e53b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversacion',
            unique_together={('usuario_1', 'usuario_2')},
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', 'fecha_envio'], name='chat_mensaj_convers_464433_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['remitente', '-fecha_envio'], name='chat_mensaj_remiten_7b0ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionchat',
            index=models.Index(fields=['usuario', 'leida'], name='chat_notifi_usuario_1bad56_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionchat',
            index=models.Index(fields=['-fecha_creacion'], name='chat_notifi_fecha_c_c5967f_idx'),
        ),
    ]
