# Generated by Django 6.0 on 2026-01-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
