# Generated by Django 6.0 on 2026-01-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_sucursal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='precio_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio mensual sugerido en Bs. (opcional)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='costo_base',
            field=models.DecimalField(decimal_places=2, help_text='Costo base por sesión en Bs.', max_digits=10),
        ),
    ]
