# Generated by Django 6.0 on 2026-01-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_tiposervicio_precio_mensual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='precio_proyecto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio para proyecto/evaluación en Bs. (opcional)', max_digits=10, null=True),
        ),
    ]
