# Generated by Django 6.0 on 2026-03-06 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_permisoedicionsesion'),
        ('servicios', '0004_tiposervicio_precio_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='es_servicio_externo',
            field=models.BooleanField(default=False, help_text='Marcar si el profesional cobra su propio precio y el centro retiene un porcentaje'),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='porcentaje_centro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% que retiene el centro por sesión. Solo para servicios externos. (ej: 10.00 = 10%)', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='ComisionSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_cobrado', models.DecimalField(decimal_places=0, help_text='Precio real cobrado al paciente en esta sesión', max_digits=10)),
                ('porcentaje_centro', models.DecimalField(decimal_places=2, help_text='% que retuvo el centro en esta sesión', max_digits=5)),
                ('monto_centro', models.DecimalField(decimal_places=0, default=0, help_text='Monto que quedó en el centro (calculado automáticamente)', max_digits=10)),
                ('monto_profesional', models.DecimalField(decimal_places=0, default=0, help_text='Monto que corresponde al profesional (calculado automáticamente)', max_digits=10)),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision', to='agenda.sesion')),
            ],
            options={
                'verbose_name': 'Comisión de Sesión',
                'verbose_name_plural': 'Comisiones de Sesiones',
            },
        ),
    ]
