# Generated by Django 6.0 on 2025-12-14 00:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('numero_transaccion', models.CharField(blank=True, help_text='Número de referencia, transacción o recibo', max_length=100)),
                ('concepto', models.CharField(help_text='Concepto del pago', max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('numero_recibo', models.CharField(help_text='Número de recibo generado automáticamente', max_length=20, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.metodopago')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pacientes.paciente')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(blank=True, help_text='Sesión específica (opcional si es pago adelantado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='agenda.sesion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField()),
                ('nombre_fiscal', models.CharField(max_length=200)),
                ('nit_ci', models.CharField(max_length=20)),
                ('concepto', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('emitida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_emitidas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='pacientes.paciente')),
                ('pagos', models.ManyToManyField(blank=True, related_name='facturas', to='facturacion.pago')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_consumido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de sesiones realizadas', max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total pagado', max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo pendiente (negativo = debe, positivo = a favor)', max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_corriente', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Cuenta Corriente',
                'verbose_name_plural': 'Cuentas Corrientes',
                'indexes': [models.Index(fields=['saldo'], name='facturacion_saldo_01a18f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['paciente', '-fecha_pago'], name='facturacion_pacient_90737c_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='facturacion_fecha_p_8ca3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['numero_recibo'], name='facturacion_numero__d7370e_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero_factura'], name='facturacion_numero__d0f299_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['paciente', '-fecha_emision'], name='facturacion_pacient_7f554e_idx'),
        ),
    ]
