# Generated by Django 6.0 on 2025-12-22 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='numero_recibo',
            field=models.CharField(help_text='Número de recibo generado automáticamente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['-numero_recibo'], name='facturacion_numero__214b68_idx'),
        ),
    ]
