# Generated by Django 6.0 on 2026-01-15 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_sesion_monto_cobrado'),
        ('facturacion', '0003_alter_pago_monto'),
        ('pacientes', '0004_paciente_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['paciente', 'anulado'], name='pago_paciente_anulado_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['paciente', 'anulado', 'sesion'], name='pago_pac_anulado_sesion_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['paciente', 'anulado', 'proyecto'], name='pago_pac_anulado_proy_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo_pago', 'anulado'], name='pago_metodo_anulado_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['sesion', 'anulado'], name='pago_sesion_anulado_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['proyecto', 'anulado'], name='pago_proyecto_anulado_idx'),
        ),
    ]
