# Generated by Django 6.0 on 2026-01-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_pago_pago_paciente_anulado_idx_and_more'),
        ('pacientes', '0004_paciente_foto'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cuentacorriente',
            index=models.Index(fields=['paciente', 'saldo'], name='facturacion_pacient_64f5b6_idx'),
        ),
    ]
