# Generated by Django 6.0 on 2026-01-24 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_remove_mensualidad_dias_semana_and_more'),
        ('facturacion', '0005_cuentacorriente_facturacion_pacient_64f5b6_idx'),
        ('pacientes', '0005_paciente_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pago',
            name='pago_sesion_o_proyecto_o_ninguno',
        ),
        migrations.AddField(
            model_name='pago',
            name='mensualidad',
            field=models.ForeignKey(blank=True, help_text='Mensualidad asociada (tratamientos mensuales regulares)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='agenda.mensualidad'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['mensualidad'], name='facturacion_mensual_e88f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['mensualidad', 'anulado'], name='pago_mensualidad_anulado_idx'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mensualidad__isnull', True), ('proyecto__isnull', True), ('sesion__isnull', False)), models.Q(('mensualidad__isnull', True), ('proyecto__isnull', False), ('sesion__isnull', True)), models.Q(('mensualidad__isnull', False), ('proyecto__isnull', True), ('sesion__isnull', True)), models.Q(('mensualidad__isnull', True), ('proyecto__isnull', True), ('sesion__isnull', True)), _connector='OR'), name='pago_sesion_o_proyecto_o_mensualidad_o_ninguno'),
        ),
    ]
