# Generated by Django 6.0 on 2026-02-01 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_mensualidad_unique_paciente_periodo'),
        ('facturacion', '0006_remove_pago_pago_sesion_o_proyecto_o_ninguno_and_more'),
        ('pacientes', '0005_paciente_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo_operacion',
            field=models.CharField(choices=[('pago', 'Pago'), ('devolucion', 'Devolución')], default='pago', help_text='Tipo de operación: Pago normal o Devolución', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['tipo_operacion', 'anulado'], name='pago_tipo_op_anulado_idx'),
        ),
    ]
