# Generated by Django 6.0 on 2026-02-03 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_mensualidad_unique_paciente_periodo'),
        ('facturacion', '0007_pago_tipo_operacion_pago_pago_tipo_op_anulado_idx'),
        ('pacientes', '0005_paciente_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devolucion', models.CharField(help_text='Número único de devolución (autogenerado)', max_length=20, unique=True)),
                ('fecha_devolucion', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField(help_text='Motivo de la devolución')),
                ('numero_transaccion', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_devolucion', '-fecha_registro'],
            },
        ),
        migrations.AlterModelOptions(
            name='cuentacorriente',
            options={'ordering': ['paciente__nombre', 'paciente__apellido'], 'verbose_name': 'Cuenta Corriente', 'verbose_name_plural': 'Cuentas Corrientes'},
        ),
        migrations.RemoveConstraint(
            model_name='pago',
            name='pago_sesion_o_proyecto_o_mensualidad_o_ninguno',
        ),
        migrations.RemoveIndex(
            model_name='cuentacorriente',
            name='facturacion_saldo_01a18f_idx',
        ),
        migrations.RemoveIndex(
            model_name='cuentacorriente',
            name='facturacion_pacient_64f5b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='facturacion_numero__d0f299_idx',
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='facturacion_pacient_7f554e_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='facturacion_fecha_p_8ca3d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='facturacion_sesion__ce52af_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='facturacion_proyect_e37d7b_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='facturacion_numero__214b68_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pago_paciente_anulado_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pago_pac_anulado_sesion_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pago_pac_anulado_proy_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pago_metodo_anulado_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pago_sesion_anulado_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pago_proyecto_anulado_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='facturacion_mensual_e88f8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pago_mensualidad_anulado_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='pago_tipo_op_anulado_idx',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='nombre_fiscal',
            new_name='razon_social',
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='num_mensualidades_activas',
            field=models.IntegerField(default=0, help_text='Mensualidades en estado activa'),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='num_proyectos_activos',
            field=models.IntegerField(default=0, help_text='Proyectos en progreso o planificados'),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='num_sesiones_programadas_pendientes',
            field=models.IntegerField(default=0, help_text='Sesiones programadas sin pagar'),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='num_sesiones_realizadas_pendientes',
            field=models.IntegerField(default=0, help_text='Sesiones realizadas/falta sin pagar completamente'),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='pagos_adelantados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pagos sin asignar (crédito a favor)', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='pagos_mensualidades',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pagos aplicados a mensualidades', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='pagos_proyectos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pagos aplicados a proyectos', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='pagos_sesiones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pagos aplicados a sesiones normales', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo solo de lo ya ocurrido', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='saldo_real',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo incluyendo todos los compromisos futuros', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='total_consumido_actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total solo de lo ya ocurrido (sin programadas ni planificadas)', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='total_consumido_real',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total incluyendo todos los compromisos', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='total_devoluciones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Devoluciones realizadas (se restan del total pagado)', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='total_mensualidades',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Mensualidades activas/pausadas/completadas', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='total_proyectos_planificados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Proyectos planificados (compromiso futuro)', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='total_proyectos_real',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Proyectos en_progreso/finalizados', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='total_sesiones_normales_real',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sesiones realizadas + falta (estados con costo ya generado)', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='total_sesiones_programadas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sesiones programadas (compromiso futuro)', max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='registrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total pagado efectivamente (pagos - devoluciones)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='anulado',
            field=models.BooleanField(default=False, help_text='Marca el pago como anulado (no se considera en cálculos)'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='concepto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(help_text='Fecha en que se realizó el pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='mensualidad',
            field=models.ForeignKey(blank=True, help_text='Mensualidad a la que se aplica este pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='agenda.mensualidad'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_recibo',
            field=models.CharField(help_text='Número único de recibo (autogenerado)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_transaccion',
            field=models.CharField(blank=True, help_text='Número de transacción bancaria (opcional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que se aplica este pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='agenda.proyecto'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pago',
            name='sesion',
            field=models.ForeignKey(blank=True, help_text='Sesión a la que se aplica este pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='agenda.sesion'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['anulado'], name='facturacion_anulado_502958_idx'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='mensualidad',
            field=models.ForeignKey(blank=True, help_text='Mensualidad de la cual se devuelve dinero', null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.mensualidad'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='metodo_devolucion',
            field=models.ForeignKey(help_text='Método por el cual se devuelve el dinero', on_delete=django.db.models.deletion.PROTECT, to='facturacion.metodopago'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto del cual se devuelve dinero', null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.proyecto'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='cuentacorriente',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='cuentacorriente',
            name='total_consumido',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='emitida_por',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='pagos',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='tipo_operacion',
        ),
    ]
