# Generated by Django 6.0 on 2026-02-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_devolucion_alter_cuentacorriente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorriente',
            name='pagos_proyectos_planificados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pagos a proyectos planificados (adelantado)', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='pagos_sesiones_programadas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pagos a sesiones programadas (adelantado)', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='pagos_sin_asignar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pagos adelantados sin asignar (adelantado puro)', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='uso_credito',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Monto usado del crédito (método 'Uso de Crédito')", max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='pagos_adelantados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Crédito disponible total (adelantado - usado)', max_digits=10),
        ),
    ]
