# Generated by Django 6.0 on 2026-02-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_cuentacorriente_pagos_proyectos_planificados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorriente',
            name='pagos_mensualidades_credito',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Pagos a mensualidades usando crédito (método 'Uso de Crédito')", max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='pagos_proyectos_credito',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Pagos a proyectos usando crédito (método 'Uso de Crédito')", max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='pagos_sesiones_credito',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Pagos a sesiones usando crédito (método 'Uso de Crédito')", max_digits=10),
        ),
    ]
