# Generated by Django 6.0 on 2026-02-11 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_mensualidad_unique_paciente_periodo'),
        ('facturacion', '0010_cuentacorriente_pagos_mensualidades_credito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePagoMasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sesion', 'Sesión'), ('proyecto', 'Proyecto'), ('mensualidad', 'Mensualidad')], help_text='Tipo de servicio pagado', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto pagado para este ítem específico', max_digits=10)),
                ('concepto', models.CharField(help_text='Descripción del ítem pagado', max_length=200)),
                ('mensualidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pago_masivo', to='agenda.mensualidad')),
                ('pago', models.ForeignKey(help_text='Pago principal al que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_masivos', to='facturacion.pago')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pago_masivo', to='agenda.proyecto')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pago_masivo', to='agenda.sesion')),
            ],
            options={
                'verbose_name': 'Detalle de Pago Masivo',
                'verbose_name_plural': 'Detalles de Pagos Masivos',
                'ordering': ['id'],
            },
        ),
    ]
