# Generated by Django 6.0 on 2026-02-13 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_mensualidad_unique_paciente_periodo'),
        ('facturacion', '0011_detallepagomasivo'),
        ('pacientes', '0005_paciente_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pago',
            name='facturacion_pacient_90737c_idx',
        ),
        migrations.RenameIndex(
            model_name='pago',
            new_name='idx_pago_numero',
            old_name='facturacion_numero__d7370e_idx',
        ),
        migrations.RenameIndex(
            model_name='pago',
            new_name='idx_pago_anulado',
            old_name='facturacion_anulado_502958_idx',
        ),
        migrations.AddIndex(
            model_name='cuentacorriente',
            index=models.Index(fields=['saldo_actual'], name='idx_cc_saldo_act'),
        ),
        migrations.AddIndex(
            model_name='cuentacorriente',
            index=models.Index(fields=['saldo_real'], name='idx_cc_saldo_real'),
        ),
        migrations.AddIndex(
            model_name='cuentacorriente',
            index=models.Index(fields=['ultima_actualizacion'], name='idx_cc_upd'),
        ),
        migrations.AddIndex(
            model_name='cuentacorriente',
            index=models.Index(fields=['saldo_actual', 'ultima_actualizacion'], name='idx_cc_saldo_fecha'),
        ),
        migrations.AddIndex(
            model_name='cuentacorriente',
            index=models.Index(condition=models.Q(('saldo_actual__lt', 0)), fields=['paciente', 'saldo_actual'], name='idx_cc_deudores'),
        ),
        migrations.AddIndex(
            model_name='detallepagomasivo',
            index=models.Index(fields=['pago'], name='idx_detmas_pago'),
        ),
        migrations.AddIndex(
            model_name='detallepagomasivo',
            index=models.Index(fields=['tipo'], name='idx_detmas_tipo'),
        ),
        migrations.AddIndex(
            model_name='detallepagomasivo',
            index=models.Index(fields=['sesion'], name='idx_detmas_sesion'),
        ),
        migrations.AddIndex(
            model_name='detallepagomasivo',
            index=models.Index(fields=['proyecto'], name='idx_detmas_proy'),
        ),
        migrations.AddIndex(
            model_name='detallepagomasivo',
            index=models.Index(fields=['mensualidad'], name='idx_detmas_mens'),
        ),
        migrations.AddIndex(
            model_name='detallepagomasivo',
            index=models.Index(fields=['tipo', 'sesion'], name='idx_detmas_tipo_ses'),
        ),
        migrations.AddIndex(
            model_name='detallepagomasivo',
            index=models.Index(fields=['tipo', 'proyecto'], name='idx_detmas_tipo_proy'),
        ),
        migrations.AddIndex(
            model_name='detallepagomasivo',
            index=models.Index(fields=['tipo', 'mensualidad'], name='idx_detmas_tipo_mens'),
        ),
        migrations.AddIndex(
            model_name='detallepagomasivo',
            index=models.Index(fields=['pago', 'tipo', 'monto'], name='idx_detmas_calc'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['numero_devolucion'], name='idx_dev_numero'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['paciente'], name='idx_dev_paciente'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['fecha_devolucion'], name='idx_dev_fecha'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['proyecto'], name='idx_dev_proyecto'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['mensualidad'], name='idx_dev_mens'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['paciente', 'fecha_devolucion'], name='idx_dev_pac_fecha'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['proyecto', 'monto'], name='idx_dev_proy_monto'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['mensualidad', 'monto'], name='idx_dev_mens_monto'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['paciente'], name='idx_pago_paciente'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='idx_pago_fecha'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo_pago'], name='idx_pago_metodo'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['paciente', 'anulado', 'fecha_pago'], name='idx_pago_pac_anul_fec'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['sesion', 'anulado'], name='idx_pago_sesion_anul'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['proyecto', 'anulado'], name='idx_pago_proy_anul'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['mensualidad', 'anulado'], name='idx_pago_mens_anul'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo_pago', 'anulado', 'fecha_pago'], name='idx_pago_metodo_valid'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(condition=models.Q(('anulado', False)), fields=['paciente', 'fecha_pago', 'monto'], name='idx_pago_valido'),
        ),
    ]
