# Generated by Django 6.0 on 2026-02-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_remove_pago_facturacion_pacient_90737c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacorriente',
            name='pagos_adelantados',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Crédito disponible total (adelantado - usado)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='pagos_mensualidades',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Pagos aplicados a mensualidades', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='pagos_mensualidades_credito',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Pagos a mensualidades usando crédito (método 'Uso de Crédito')", max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='pagos_proyectos',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Pagos aplicados a proyectos', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='pagos_proyectos_credito',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Pagos a proyectos usando crédito (método 'Uso de Crédito')", max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='pagos_proyectos_planificados',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Pagos a proyectos planificados (adelantado)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='pagos_sesiones',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Pagos aplicados a sesiones normales', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='pagos_sesiones_credito',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Pagos a sesiones usando crédito (método 'Uso de Crédito')", max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='pagos_sesiones_programadas',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Pagos a sesiones programadas (adelantado)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='pagos_sin_asignar',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Pagos adelantados sin asignar (adelantado puro)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Saldo solo de lo ya ocurrido', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='saldo_real',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Saldo incluyendo todos los compromisos futuros', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='total_consumido_actual',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Total solo de lo ya ocurrido (sin programadas ni planificadas)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='total_consumido_real',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Total incluyendo todos los compromisos', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='total_devoluciones',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Devoluciones realizadas (se restan del total pagado)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='total_mensualidades',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Mensualidades activas/pausadas/completadas', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='total_pagado',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Total pagado efectivamente (pagos - devoluciones)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='total_proyectos_planificados',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Proyectos planificados (compromiso futuro)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='total_proyectos_real',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Proyectos en_progreso/finalizados', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='total_sesiones_normales_real',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Sesiones realizadas + falta (estados con costo ya generado)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='total_sesiones_programadas',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Sesiones programadas (compromiso futuro)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuentacorriente',
            name='uso_credito',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Monto usado del crédito (método 'Uso de Crédito')", max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepagomasivo',
            name='monto',
            field=models.DecimalField(decimal_places=0, help_text='Monto pagado para este ítem específico', max_digits=10),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='descuento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
