# Generated by Django 6.0 on 2026-03-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_alter_cuentacorriente_pagos_adelantados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorriente',
            name='ingreso_neto_centro',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Ingreso real del centro = total_pagado - total_devoluciones - total_profesionales', max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='total_profesionales',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Total a pagar a profesionales externos (suma de ComisionSesion.monto_profesional)', max_digits=10),
        ),
    ]
