# Generated by Django 6.0 on 2026-03-23 04:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0005_tiposervicio_es_servicio_externo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolamientoFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente — primer login no realizado'), ('enrolado', 'Enrolado'), ('bloqueado', 'Bloqueado — 3 intentos fallidos')], default='pendiente', max_length=20)),
                ('vector_facial', models.JSONField(blank=True, help_text='Embeddings del rostro', null=True)),
                ('intentos_fallidos', models.PositiveIntegerField(default=0)),
                ('fecha_enrolamiento', models.DateTimeField(blank=True, null=True)),
                ('score_promedio', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrolamiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrolamiento facial',
                'verbose_name_plural': 'Enrolamientos faciales',
            },
        ),
        migrations.CreateModel(
            name='PermisoReenrolamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_otorgado', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_usado', models.DateTimeField(blank=True, null=True)),
                ('enrolamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='asistencia.enrolamientofacial')),
                ('otorgado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_reenrolamiento_otorgados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de re-enrolamiento',
                'verbose_name_plural': 'Permisos de re-enrolamiento',
                'ordering': ['-fecha_otorgado'],
            },
        ),
        migrations.CreateModel(
            name='ZonaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Sede Central, Domicilio Paciente López', max_length=150)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radio_metros', models.PositiveIntegerField(default=100, help_text='Radio en metros desde el centro. Configurable por zona.')),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(blank=True, help_text='Sucursal de referencia (opcional, solo para identificación)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas_asistencia', to='servicios.sucursal')),
            ],
            options={
                'verbose_name': 'Zona de asistencia',
                'verbose_name_plural': 'Zonas de asistencia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HorarioPredeterminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.TimeField(default='08:00')),
                ('hora_salida', models.TimeField(default='17:00')),
                ('tolerancia_minutos', models.PositiveIntegerField(default=10, help_text='Minutos de gracia después de la hora de entrada')),
                ('zona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horario_predeterminado', to='asistencia.zonaasistencia')),
            ],
            options={
                'verbose_name': 'Horario predeterminado',
                'verbose_name_plural': 'Horarios predeterminados',
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('estado', models.CharField(choices=[('PUNTUAL', 'Puntual'), ('TARDANZA', 'Tardanza'), ('AUSENTE', 'Ausente'), ('DENEGADO_GPS', 'Denegado — fuera de zona'), ('DENEGADO_BIO', 'Denegado — biométrico fallido')], max_length=15)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distancia_metros', models.FloatField(blank=True, null=True)),
                ('biometrico_score', models.FloatField(blank=True, null=True)),
                ('foto_captura', models.ImageField(blank=True, null=True, upload_to='asistencia/capturas/%Y/%m/%d/')),
                ('minutos_tardanza', models.IntegerField(default=0, help_text='Minutos de diferencia respecto al horario. Base para sueldos.')),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('observacion', models.TextField(blank=True, help_text='Opcional. Solo editable durante el día del registro. Visible para el profesional y el admin.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='asistencia.zonaasistencia')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['user', 'fecha_hora'], name='asistencia__user_id_d6f0fc_idx'), models.Index(fields=['estado', 'fecha_hora'], name='asistencia__estado_e01fee_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfigAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada_custom', models.TimeField(blank=True, null=True)),
                ('hora_salida_custom', models.TimeField(blank=True, null=True)),
                ('tolerancia_custom', models.PositiveIntegerField(blank=True, null=True)),
                ('personalizado', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, help_text='UUID del celular autorizado', max_length=255)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_asistencia', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_asistencia', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='asistencia.zonaasistencia')),
            ],
            options={
                'verbose_name': 'Configuración de asistencia',
                'verbose_name_plural': 'Configuraciones de asistencia',
                'unique_together': {('user', 'zona')},
            },
        ),
    ]
