# Generated by Django 6.0 on 2026-03-23 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        ('servicios', '0005_tiposervicio_es_servicio_externo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configasistencia',
            options={'verbose_name': 'Configuracion de asistencia', 'verbose_name_plural': 'Configuraciones de asistencia'},
        ),
        migrations.AddField(
            model_name='configasistencia',
            name='dias_continuo_custom',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configasistencia',
            name='dias_partido_custom',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configasistencia',
            name='hora_entrada_tarde_custom',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configasistencia',
            name='hora_salida_tarde_custom',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configasistencia',
            name='tolerancia_tarde_custom',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariopredeterminado',
            name='dias_continuo',
            field=models.JSONField(default=list, help_text='Dias con horario continuo. Ej: ["SAB"]'),
        ),
        migrations.AddField(
            model_name='horariopredeterminado',
            name='dias_partido',
            field=models.JSONField(default=list, help_text='Dias con horario partido. Ej: ["LUN","MAR","MIE","JUE","VIE"]'),
        ),
        migrations.AddField(
            model_name='horariopredeterminado',
            name='hora_entrada_tarde',
            field=models.TimeField(blank=True, default='14:00', null=True),
        ),
        migrations.AddField(
            model_name='horariopredeterminado',
            name='hora_salida_tarde',
            field=models.TimeField(blank=True, default='18:00', null=True),
        ),
        migrations.AddField(
            model_name='horariopredeterminado',
            name='tolerancia_tarde',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='bloque',
            field=models.CharField(blank=True, choices=[('manana', 'Manana'), ('tarde', 'Tarde'), ('continuo', 'Continuo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='configasistencia',
            name='device_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enrolamientofacial',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enrolado', 'Enrolado'), ('bloqueado', 'Bloqueado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrolamientofacial',
            name='vector_facial',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horariopredeterminado',
            name='hora_salida',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AlterField(
            model_name='horariopredeterminado',
            name='tolerancia_minutos',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('PUNTUAL', 'Puntual'), ('TARDANZA', 'Tardanza'), ('AUSENTE', 'Ausente'), ('DENEGADO_GPS', 'Denegado GPS'), ('DENEGADO_BIO', 'Denegado biometrico')], max_length=15),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='minutos_tardanza',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='zonaasistencia',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='zonaasistencia',
            name='radio_metros',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='zonaasistencia',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal de referencia (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas_asistencia', to='servicios.sucursal'),
        ),
        migrations.CreateModel(
            name='FechaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_horario', models.CharField(choices=[('continuo', 'Horario continuo'), ('partido', 'Horario partido'), ('libre', 'Dia libre')], max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechas_especiales_creadas', to=settings.AUTH_USER_MODEL)),
                ('profesionales', models.ManyToManyField(blank=True, help_text='Dejar vacio para aplicar a todos los profesionales de la zona', related_name='fechas_especiales', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_especiales', to='asistencia.zonaasistencia')),
            ],
            options={
                'verbose_name': 'Fecha especial',
                'verbose_name_plural': 'Fechas especiales',
                'ordering': ['-fecha'],
                'unique_together': {('zona', 'fecha')},
            },
        ),
    ]
