# Generated by Django 6.0 on 2026-03-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_configasistencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechaespecial',
            name='hora_entrada_especial',
            field=models.TimeField(blank=True, help_text='Dejar vacio para usar el horario base de la zona', null=True),
        ),
        migrations.AddField(
            model_name='fechaespecial',
            name='hora_entrada_tarde_especial',
            field=models.TimeField(blank=True, help_text='Solo para tipo partido. Dejar vacio para usar el horario base.', null=True),
        ),
        migrations.AddField(
            model_name='fechaespecial',
            name='hora_salida_especial',
            field=models.TimeField(blank=True, help_text='Dejar vacio para usar el horario base de la zona', null=True),
        ),
        migrations.AddField(
            model_name='fechaespecial',
            name='hora_salida_tarde_especial',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fechaespecial',
            name='tolerancia_especial',
            field=models.PositiveIntegerField(blank=True, help_text='Dejar vacio para usar la tolerancia base de la zona', null=True),
        ),
        migrations.AddField(
            model_name='fechaespecial',
            name='tolerancia_tarde_especial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
