# Generated by Django 6.0 on 2026-03-23 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_fechaespecial_hora_entrada_especial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Si no es null, este registro fue creado manualmente por un administrador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_marcados', to=settings.AUTH_USER_MODEL),
        ),
    ]
