# Generated by Django 6.0 on 2026-07-24 21:20

import archivos_centro.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_archivo_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de Archivo',
                'verbose_name_plural': 'Categorías de Archivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre descriptivo del archivo', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='archivos_centro/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'txt', 'jpg', 'jpeg', 'png', 'webp', 'xls', 'xlsx', 'csv', 'ppt', 'pptx', 'zip', 'rar']), archivos_centro.models.validar_tamano_archivo])),
                ('visibilidad', models.CharField(choices=[('privado', 'Solo quien lo subió'), ('todos', 'Todos en el centro'), ('roles', 'Solo ciertos roles (definido por admin)'), ('usuarios', 'Solo ciertos usuarios (definido por admin)')], default='privado', max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_centro_subidos', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='archivos_centro.categoriaarchivo')),
            ],
            options={
                'verbose_name': 'Archivo del Centro',
                'verbose_name_plural': 'Archivos del Centro',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoRolPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('paciente', 'Paciente'), ('profesional', 'Profesional'), ('recepcionista', 'Recepcionista'), ('gerente', 'Gerente')], max_length=20)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_permitidos', to='archivos_centro.archivocentro')),
            ],
            options={
                'verbose_name': 'Rol permitido en archivo',
                'verbose_name_plural': 'Roles permitidos en archivo',
                'unique_together': {('archivo', 'rol')},
            },
        ),
        migrations.CreateModel(
            name='ArchivoUsuarioPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_permitidos', to='archivos_centro.archivocentro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_centro_autorizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario permitido en archivo',
                'verbose_name_plural': 'Usuarios permitidos en archivo',
                'unique_together': {('archivo', 'usuario')},
            },
        ),
        migrations.AddIndex(
            model_name='archivocentro',
            index=models.Index(fields=['-fecha_subida'], name='archivos_ce_fecha_s_902f59_idx'),
        ),
        migrations.AddIndex(
            model_name='archivocentro',
            index=models.Index(fields=['categoria'], name='archivos_ce_categor_b42bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='archivocentro',
            index=models.Index(fields=['subido_por'], name='archivos_ce_subido__d39e86_idx'),
        ),
    ]
