# Generated by Django 6.0 on 2026-01-14 16:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Foto del profesional (se optimizará automáticamente)', max_length=255, null=True, verbose_name='foto'),
        ),
    ]
