# Generated by Django 6.0 on 2025-12-16 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='sucursal',
            field=models.ForeignKey(default=1, help_text='Sucursal donde trabaja el profesional', on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='servicios.sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profesional',
            name='servicios',
            field=models.ManyToManyField(help_text='Servicios/terapias que este profesional puede ofrecer', related_name='profesionales', to='servicios.tiposervicio'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario del sistema para este profesional', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['sucursal', 'activo'], name='profesional_sucursa_eae575_idx'),
        ),
    ]
