# Generated by Django 6.0 on 2025-12-16 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_profesional_sucursal_alter_profesional_servicios_and_more'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profesional',
            name='profesional_sucursa_eae575_idx',
        ),
        migrations.AddField(
            model_name='profesional',
            name='sucursales',
            field=models.ManyToManyField(help_text='Sucursales donde trabaja el profesional', related_name='profesionales', to='servicios.sucursal'),
        ),
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['activo'], name='profesional_activo_d318f9_idx'),
        ),
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['apellido', 'nombre'], name='profesional_apellid_095ea1_idx'),
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='sucursal',
        ),
    ]
